# Use an official Node.js image as the base image
FROM node:latest

WORKDIR /app

ARG REACT_APP_NEWS_API_BASE_URL
ARG REACT_APP_NEWS_API_KEY
ARG REACT_APP_NYT_API_BASE_URL
ARG REACT_APP_NYT_API_KEY
ARG REACT_APP_GUARDIAN_API_BASE_URL
ARG REACT_APP_GUARDIAN_API_KEY

COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

COPY . .

ENV REACT_APP_NEWS_API_BASE_URL=${REACT_APP_NEWS_API_BASE_URL}
ENV REACT_APP_NEWS_API_KEY=${REACT_APP_NEWS_API_KEY}
ENV REACT_APP_NYT_API_BASE_URL=${REACT_APP_NYT_API_BASE_URL}
ENV REACT_APP_NYT_API_KEY=${REACT_APP_NYT_API_KEY}
ENV REACT_APP_GUARDIAN_API_BASE_URL=${REACT_APP_GUARDIAN_API_BASE_URL}
ENV REACT_APP_GUARDIAN_API_KEY=${REACT_APP_GUARDIAN_API_KEY}



EXPOSE 3000

CMD ["npm", "start"]