export const NYTSectionOptions = [
    { id: 'arts', label: 'Arts' },
    { id: 'automobiles', label: 'Automobiles' },
    { id: 'books/review', label: 'Books/Review' },
    { id: 'business', label: 'Business' },
    { id: 'fashion', label: 'Fashion' },
    { id: 'food', label: 'Food' },
    { id: 'health', label: 'Health' },
    { id: 'home', label: 'Home' },
    { id: 'insider', label: 'Insider' },
    { id: 'magazine', label: 'Magazine' },
    { id: 'movies', label: 'Movies' },
    { id: 'nyregion', label: 'NY Region' },
    { id: 'obituaries', label: 'Obituaries' },
    { id: 'opinion', label: 'Opinion' },
    { id: 'politics', label: 'Politics' },
    { id: 'realestate', label: 'Real Estate' },
    { id: 'science', label: 'Science' },
    { id: 'sports', label: 'Sports' },
    { id: 'sundayreview', label: 'Sunday Review' },
    { id: 'technology', label: 'Technology' },
    { id: 'theater', label: 'Theater' },
    { id: 't-magazine', label: 'T Magazine' },
    { id: 'travel', label: 'Travel' },
    { id: 'upshot', label: 'Upshot' },
    { id: 'us', label: 'US' },
    { id: 'world', label: 'World' },
];
export const NewCategoryArray = [
    { id: 'business', label: 'Business' },
    { id: 'entertainment', label: 'Entertainment' },
    { id: 'general', label: 'General' },
    { id: 'health', label: 'Health' },
    { id: 'sciences', label: 'Sciences' },
    { id: 'sports', label: 'Sports' },
    { id: 'technology', label: 'Technology' },
];
